### ISSUE TITLE
Update installation for 3.0.x

### ISSUE THREAD

**Issue by AlainJanssens** [fritz-hh/OCRmyPDF#113]
The description to install OCRmyPDF to ubuntu is not up-to-date any more..(installation of ghostscript is not there ;-) ).

Maybe you could deliver a 'Dockerfile' that is installing everything...

Regards,

Alain

**Comment by jbarlow83** [comment]
Will do - already in the works.

**Comment by AlainJanssens** [comment]
Looking forward :+1:

**Comment by jbarlow83** [comment]
I released a new version with a Docker container today. Let me know what you think.

**Comment by AlainJanssens** [comment]
The apt-get is still getting an older version of tesseract (3.02). In the meantime there is already 3.04

**Comment by jbarlow83** [comment]
It's up to your platform vendor to update their packages. You could try the
Docker container which has 3.04 or compile Tesseract from source.

**Comment by jbarlow83** [comment]
Another option would be add to a PPA. Looks like people have built newer Tesseracts for your Ubuntu.
https://launchpad.net/ubuntu/+ppas?name_filter=tesseract
